### ISSUE TITLE
Google Lighthouse performance score of over 75

### ISSUE THREAD

**Issue by mikeflof** [JR-prog/Interlinked_SOEN390_Team11#236]
### Description
InterLinked will be have a Google Lighthouse performance score of over 75 to ensure high speeds

Story points: 1
Priority: High
Risk: Low

**Comment by JR-prog** [comment]
Done! Check it out :eyes:

![image](https://user-images.githubusercontent.com/52092026/233812339-27466a51-6a10-4a73-b03d-129324b4c8d2.png)
